spring:
  profiles:
    include: oauth

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/test?serverTimezone=Asia/Seoul
    username: root
    password: qwerqwer

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

    thymeleaf:
      cache: false